name: ramp-tephra
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy==1.23
  - scipy
  - pandas
  - scikit-learn>=0.22
  - missingno
  - matplotlib
  - seaborn
  - ipywidgets
  - joblib
  - lightgbm
  - xgboost
  - catboost
  - tensorflow-cpu
  - pytorch-cpu
  - torchvision-cpu
  - category_encoders
  
  - pip
  - pip:
    - ramp-workflow==0.6.0
    - osfclient
